version: '3'

services:
  project_share:
    container_name: project_share
    build: $PWD
    volumes:
      - $PWD:/project-share
    working_dir: /project-share/
    command: "yarn dev"
    environment:
      - HOST=0.0.0.0
    ports: 
      - 5000:5000
  # comment out below if not working with API
  api:
    container_name: ieeeutd_api
    build: ../api-ieee/images/api/
    volumes:
      - ../api-ieee:/ieeeutd-api/
      - ../api-ieee:/ieeeutd-api/.git/
    working_dir: /ieeeutd-api/
    command: npm run dev
    environment:
      - SESSION_SECRET=aASKF4AFjas52wFSAF
      - CACHE_HOST=cache
      - MAIL_HOSTNAME=http://dev.ieeeutd.org
      - DATABASE_PORT_27017_TCP_ADDR=database
    ports:
      - "8000:3000"
    links:
      - database
      - cache
  nginx:
    container_name: ieeeutd_nginx
    image: nginx
    volumes:
      - ./images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
      - project_share
  database:
    container_name: ieeeutd_db
    image: mongo:4.0
    ports:
      - "27000:27017"
  cache:
    container_name: ieeeutd_cache
    image: redis