version: '3'

services:
  project_share:
    container_name: project_share
    build: $PWD
    volumes:
      - $PWD:/project-share
    working_dir: /project-share/
    command: "yarn dev"
    environment:
      - HOST=0.0.0.0
    ports: 
      - 5000:5000
